name: First workflow
on:
  push:
    branches:
      - '**'
      
  workflow_dispatch:
      
      
jobs:
  service:
    uses: artechorg/common-workflows/.github/workflows/common-workflows.yaml@main
    with:
      test_data: ""
      event_inputs: ${{ github.event.inputs == '' && '{}' || toJson(github.event.inputs) }}
    secrets:
      FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
